CREATE TABLE VEHICLES 
(
  VEHICLE_NO VARCHAR2(40) NOT NULL 
, MODEL_NAME VARCHAR2(20) 
, MANUFACTURER VARCHAR2(20) 
, REGISTRATION_NO VARCHAR2(20) NOT NULL 
, COLOR VARCHAR2(20) 
, FUEL_TYPE VARCHAR2(20) 
, LEASE_AMOUNT FLOAT 
, CONSTRAINT VEHICLES_PK PRIMARY KEY 
  (
    VEHICLE_NO 
  )
  ENABLE 
);
