CREATE TABLE BUS 
(
  BUS_NO INT NOT NULL 
, BUS_TYPE VARCHAR2(40) 
, REGISTRATION_NO VARCHAR2(40) 
, FUEL_TYPE VARCHAR2(40) 
, COLOR VARCHAR2(20) 
, CAPACITY INT 
, CONSTRAINT BUS_PK PRIMARY KEY 
  (
    BUS_NO 
  )
  ENABLE 
);
